### ISSUE TITLE
How to upload Docker images to VagrantCloud?

### ISSUE THREAD

**Issue by marven-lim** [tknerr/vagrant-docker-baseimages#23]
I want to upload docker images to VagrantCloud but has been unable to do so, may I know how you upload yours to VagrantCloud?

**Comment by tknerr** [comment]
Hi @marven-lim, in fact the docker images are not hosted on VagrantCloud, but on DockerHub. 

VagrantCloud contains only the .box file (a zip file actually) which [references](https://github.com/tknerr/vagrant-docker-baseimages/blob/master/Rakefile#L57) the docker image on DockerHub.

E.g. for ubuntu-20.04:

* the .box file: https://app.vagrantup.com/tknerr/boxes/baseimage-ubuntu-20.04
* the docker image referenced from within the .box: https://hub.docker.com/r/tknerr/baseimage-ubuntu/tags/?page=1&name=20.04
