### ISSUE TITLE
what's the username/password of you docker base image?

### ISSUE THREAD

**Issue by zhangzhanhui** [tknerr/vagrant-docker-baseimages#6]
hi, there

I executed "vagrant init tknerr/baseimage-ubuntu-14.04", and "vagrant init tknerr/baseimage-ubuntu-14.04" .but i have no password of user docker, so I can't login.

could you tell me something about it.

**Comment by tknerr** [comment]
Hi @zhangzhanhui , sorry for the delay. These docker images / baseboxes follow the standard conventions for vagrant baseboxes and add a user "vagrant" with password "vagrant". See here:
https://github.com/tknerr/vagrant-docker-baseimages/blob/master/ubuntu-1404/Dockerfile#L19

You can also log in simply via `vagrant ssh` which won't ask you for a password and logs with the default vagrant insecure key, see
https://github.com/tknerr/vagrant-docker-baseimages/blob/master/ubuntu-1404/Dockerfile#L26-L32

HTH, Torben

**Comment by zhangzhanhui** [comment]
Thanks to hear from you.
I tried docker/docker because I got prompt message that the user is docker
when I up tknerr/vagrant.
I tried vagrant/vagrant as other boxes too.
But they all not work. :(

I'll try vagrant ssh sometime.

thanks again.


Enjoy my life every day!



2016-11-20 5:17 GMT+08:00 Torben Knerr <notifications@github.com>:
